### ISSUE TITLE
BSD malloc factoids

### ISSUE THREAD

**Issue by fanf2** [nabijaczleweli/nabijaczleweli.github.io#2]
Thanks for this article https://nabijaczleweli.xyz/content/blogn_t/017-malloc0.html

It’s a nicely thorough history.

Here are a few extra notes on the BSDs…

The CSRG SCCS repository converted to svn is available to browse on FreeBSD’s svnweb server so you can see the malloc implementation, tho this doesn’t add much to your summary - https://svnweb.freebsd.org/csrg/lib/libc/stdlib/malloc.c?revision=61180&view=markup

It has the malloc(0) != 0 && realloc(ptr, 0) != 0 behaviour

There’s a 4.4BSD realloc() manual https://man.freebsd.org/cgi/man.cgi?query=realloc&apropos=0&sektion=0&manpath=4.4BSD+Lite2&arch=default&format=html

It closely matches the C89 wording which is *not* what the implementation does

Unlike the other BSDs, NetBSD was changed to match C89 in 1996 http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libc/stdlib/malloc.c?rev=1.6 then changed back when they switched to phkmalloc in 1999 http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libc/stdlib/malloc.c?rev=1.17;content-type=text%2Fx-cvsweb-markup

**Comment by nabijaczleweli** [comment]
It's cute if you don't have the ISOs, but to me "some random SVN(!) repository" isn't really archival-grade or citation-grade, likewise "running Some file through mandoc in man-cgi".

The NetBSD thing is funny, but out-of-scope for 017 (it's bad enough that 4.4BSD-Lite2 includes NetBSD code (this factors into [015](https://nabijaczleweli.xyz/content/blogn_t/015-ranlib.html) but not 017 thankfully)).

4.4BSD realloc(3) saying it frees but not doing so is definitely in scope, and looks to be missing, I'll update this.

**Comment by nabijaczleweli** [comment]
Thanks for the review, 4.4BSD's realloc documentation fiasco documented in 8bc1f37a1f5394f0fbf1653488939ba4596c3f5a
