### ISSUE TITLE
ISO C realloc wording

### ISSUE THREAD

**Issue by fanf2** [nabijaczleweli/nabijaczleweli.github.io#3]
I've been looking around for more on the wording changes to realloc() in various versions of the C standard

The document log https://www.open-std.org/JTC1/SC22/WG14/www/docs/ has some references to realloc() wording changes in the meeting minutes around 1998 / 1999, but there's no record of what issue they were trying to fix in C99 nor any notes on the discussion. The discussion since then has been recorded in more detail.

Regarding C89, [the rationale](https://www.open-std.org/JTC1/SC22/WG14/www/docs/n850.pdf) is more informative:

> Some implementations have returned non-null values for allocation requests of zero bytes. Although this strategy has the theoretical advantage of distinguishing between “nothing” and “zero” (an unallocated pointer vs. a pointer to zero-length space), it has the more compelling theoretical disadvantage of requiring the concept of a zero-length object. Since such objects cannot be declared, the only way they could come into existence would be through such allocation requests.
>
> The C89 Committee has decided not to accept the idea of zero-length objects. The allocation functions may therefore return a null pointer for an allocation request of zero bytes. Note that this treatment does not preclude the paradigm outlined above.
>
> **QUIET CHANGE IN C89**
>
> A program which relies on size-zero allocation requests returning a non-null pointer will behave differently.

wording in C89 https://port70.net/~nsz/c/c89/c89-draft.html

> ... If the space cannot be allocated, a null pointer is returned. If the size of the space requested is zero, the behavior is implementation-defined; the value returned shall be either a null pointer or a unique pointer. ...

> The realloc function changes the size of the object pointed to by ptr to the size specified by size. ... If the space cannot be allocated, the object pointed to by ptr is unchanged. If size is zero and ptr is not a null pointer, the object it points to is freed.

> The realloc function returns either a null pointer or a pointer to the possibly moved allocated space.

C99 TC3 https://www.open-std.org/JTC1/SC22/WG14/www/docs/n1256.pdf and C11 n1570

> ... If the space cannot be allocated, a null pointer is returned. If the size of the space requested is zero, the behavior is implementation- defined: either a null pointer is returned, or the behavior is as if the size were some nonzero value, except that the returned pointer shall not be used to access an object.

> The realloc function deallocates the old object pointed to by ptr and returns a pointer to a new object that has the size specified by size. ...

> ... If memory for the new object cannot be allocated, the old object is not deallocated and its value is unchanged.

(no mention of size == 0)

> The realloc function returns a pointer to the new object (which may have the same value as a pointer to the old object), or a null pointer if the new object could not be allocated.

C17 n2176

> ...  If the space cannot be allocated, a null pointer is returned. If the size of the space requested is zero, the behavior is implementation-defined: either a null pointer is returned to indicate an error, or the behavior is as if the size were some nonzero value, except that the returned pointer shall not be used to access an object.

> The realloc function deallocates the old object pointed to by ptr and returns a pointer to a new object that has the size specified by size.  ...

> ... If size is nonzero and memory for the new object is not allocated, the old object is not deallocated. If size is zero and memory for the new object is not allocated, it is implementation-defined whether the old object is deallocated. If the old object is not deallocated, its value shall be unchanged.

> The realloc function returns a pointer to the new object (which may have the same value as a pointer to the old object), or a null pointer if the new object has not been allocated.

C23 n3299

>  If the space cannot be allocated, a null pointer is returned. If the size of the space requested is zero, the behavior is implementation-defined: either a null pointer is returned to indicate an error, or the behavior is as if the size were some nonzero value, except that the returned pointer shall not be used to access an object.

> The realloc function deallocates the old object pointed to by ptr and returns a pointer to a new object that has the size specified by size. ...

> ...  if ptr does not match a pointer earlier returned by a memory management function, or if the space has been deallocated by a call to the free or realloc function, or if the size is zero, the behavior is undefined. If memory for the new object is not allocated, the old object is not deallocated and its value is unchanged.

> The realloc function returns a pointer to the new object (which can have the same value as a pointer to the old object), or a null pointer if the new object has not been allocated.

**Comment by nabijaczleweli** [comment]
I'll cross-link to this as a curiosum, but this is out of scope for 017 proper; may be of interest for @alejandro-colomar if his paper is still alive though

**Comment by nabijaczleweli** [comment]
Thanks, linked in 8bc1f37a1f5394f0fbf1653488939ba4596c3f5a.

**Comment by alejandro-colomar** [comment]
Hi nab,

On Wed, Oct 30, 2024 at 10:32:40AM -0700, наб wrote:
> I'll cross-link to this as a curiosum, but this is out of scope for
> 017 proper; may be of interest for @alejandro-colomar if his paper is
> still alive though

It's not yet born.  :)  But yeah, I'll do something.

BTW, I'm back to Middle Age here in Aldaya, so I can't even load the
github page.  Crappy internet, no electricity, no water.  I won't
respond to most stuff in some week or so.

Thanks for the CC!

Have a lovely night!
Alex

-- 
<https://www.alejandro-colomar.es/>
